<?php

/**
 * @file
 * Implementation of Entity Hax Element.
 */

/**
 * Implements hook_entity_info().
 */
function hax_element_entity_info() {
  $return['hax_element'] = array(
    'label' => t('Hax Element'),
    // The entity class and controller class extend the default entity classes.
    'entity class' => 'HaxElement',
    'controller class' => 'HaxElementController',
    'base table' => 'hax_element',
    'fieldable' => TRUE,
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'hax_element_id',
      'bundle' => 'type',
    ),
    // Bundles are defined by the types below.
    'bundles' => array(),
    'bundle keys' => array('bundle' => 'type'),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'access callback' => 'hax_element_access',
    'module' => 'hax_element',
    // The information below is used by the Controller;
    // which extends the EntityDefaultUIController.
    'admin ui' => array(
      'path' => 'admin/content/hax_element',
      'file' => 'includes/hax_element.admin.inc',
      'controller class' => 'HaxElementUIController',
      'menu wildcard' => '%hax_element',
    ),
  );
  // The entity that holds information about the entity types.
  $return['hax_element_type'] = array(
    'label' => t('Hax Element Type'),
    'entity class' => 'HaxElementType',
    'controller class' => 'HaxElementTypeController',
    'base table' => 'hax_element_type',
    'fieldable' => FALSE,
    'bundle of' => 'hax_element',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'hax_element_type_access',
    'module' => 'hax_element',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/hax_element_types',
      'file' => 'includes/hax_element_type.admin.inc',
      'controller class' => 'HaxElementTypeUIController',
    ),
  );

  return $return;
}

/**
 * Implements hook_entity_info_alter().
 */
function hax_element_entity_info_alter(&$entity_info) {
  foreach (hax_element_get_types() as $type => $info) {
    $entity_info['hax_element']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/hax_element_types/manage/%hax_element_type',
        'real path' => 'admin/structure/hax_element_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer Hax Element types'),
      ),
    );
  }
}

/**
 * Implements hook_permission().
 */
function hax_element_permission() {
  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity.
  $permissions = array(
    'administer Hax Element types' => array(
      'title' => t('Administer Hax Element types'),
      'description' => t('Create and delete fields for Hax Element types, and set their permissions.'),
    ),
    'administer Hax Element' => array(
      'title' => t('Administer Hax Element'),
      'description' => t('Edit and delete all Hax Element'),
    ),
  );

  // Generate permissions.
  foreach (hax_element_get_types() as $type) {
    $type_name = check_plain($type->type);
    $permissions += array(
      "edit any $type_name Hax Element" => array(
        'title' => t('%type_name: Edit any Hax Element', array('%type_name' => $type->label)),
      ),
      "view any $type_name Hax Element" => array(
        'title' => t('%type_name: View any Hax Element', array('%type_name' => $type->label)),
      ),
    );
  }

  return $permissions;
}

/**
 * Implements hook_theme().
 */
function hax_element_theme() {
  return array(
    'hax_element' => array(
      'render element' => 'elements',
      'template' => 'hax_element',
    ),
  );
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function hax_element_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/structure/hax_element/add'
  // on 'admin/structure/hax_element'.
  if ($root_path == 'admin/content/hax_element') {
    $item = menu_get_item('admin/content/hax_element/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Determines whether the given user has access to a Hax Element.
 *
 * @param string $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 *
 * @param object $entity
 *   Optionally a Hax Element or a Hax Element type to check access for.
 *   If nothing is given, access for all Hax Element is determined.
 *
 * @param object $account
 *   The user to check for. Leave it to NULL to check for the global user.
 *
 * @return bool
 *   Whether access is allowed or not.
 */
function hax_element_access($op, $entity = NULL, $account = NULL) {
  if (user_access('administer Hax Element', $account)) {
    return TRUE;
  }

  if (isset($entity) && $type_name = $entity->type) {
    $op = ($op == 'view') ? 'view' : 'edit';
    if (user_access("$op any $type_name Hax Element", $account)) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Access callback for the entity API.
 */
function hax_element_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer Hax Element types', $account);
}

/**
 * Gets an array of all Hax Element types, keyed by the type name.
 *
 * @param string $type_name
 *   If set, the type with the given name is returned.
 *
 * @return array
 *   Depending whether $type isset, an array of Hax Element types
 *   or a single one.
 */
function hax_element_get_types($type_name = NULL) {
  // entity_load will get the Entity controller for our Hax Element entity
  // and call the load function of that object.
  // We are loading entities by name here.
  $types = entity_load_multiple_by_name('hax_element_type', isset($type_name) ? array($type_name) : FALSE);

  return isset($type_name) ? reset($types) : $types;
}

/**
 * Menu argument loader; Load a Hax Element type by string.
 *
 * @param string $type
 *   The machine-readable name of a Hax Element type to load.
 *
 * @return mixed
 *   A Hax Element type array or FALSE if $type does not exist.
 */
function hax_element_type_load($type) {
  return hax_element_get_types($type);
}

/**
 * Fetch a Hax Element object.
 *
 * @param int $hax_element_id
 *   Integer specifying the hax_element id.
 *
 * @return object
 *   A fully-loaded object or FALSE if it cannot be loaded.
 *
 * @see entity_load_single()
 */
function hax_element_load($hax_element_id) {
  return entity_load_single('hax_element', $hax_element_id);
}

/**
 * Load multiple Hax Element based on certain conditions.
 *
 * @param array $hax_element_ids
 *   An array of Hax Element IDs.
 *
 * @param array $conditions
 *   An array of conditions to match against the hax_element table.
 *
 * @param bool $reset
 *   A boolean indicating that the internal cache should be reset.
 *
 * @return array
 *   An array of objects, indexed by hax_element_id.
 *
 * @see entity_load()
 * @see hax_element_load()
 */
function hax_element_load_multiple($hax_element_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('hax_element', $hax_element_ids, $conditions, $reset);
}

/**
 * Deletes a Hax Element.
 */
function hax_element_delete(HaxElement $hax_element) {
  $hax_element->delete();
}

/**
 * Delete multiple Hax Element.
 *
 * @param array $hax_element_ids
 *   An array of Hax Element IDs.
 */
function hax_element_delete_multiple(array $hax_element_ids) {
  return entity_delete_multiple('hax_element', $hax_element_ids);
}

/**
 * Create a Hax Element object.
 */
function hax_element_create($values = array()) {
  return entity_create('hax_element', $values);
}

/**
 * Saves a Hax Element to the database.
 *
 * @param string $hax_element
 *   The Hax Element object.
 */
function hax_element_save($hax_element) {
  return entity_save('hax_element', $hax_element);
}

/**
 * Saves a Hax Element type to the db.
 */
function hax_element_type_save($type) {
  return entity_save('hax_element_type', $type);
}

/**
 * Deletes a Hax Element type from the db.
 */
function hax_element_type_delete(HaxElementType $type) {
  $type->delete();
}

/**
 * Menu title callback for showing individual entities.
 */
function hax_element_page_title(HaxElement $hax_element) {
  return $hax_element->label;
}

/**
 * Sets up content to show an individual Hax Element.
 */
function hax_element_page_view($hax_element, $view_mode = 'full') {
  return entity_view('hax_element_type', array($hax_element), $view_mode);
}
