<?php

/**
 * @file
 * Entity Scaffold hooks implementation.
 */

define('ENTITY_SCAFFOLD_MODEL_MODULE_PATH', drupal_get_path('module', 'entity_scaffold') . '/model/');
define('ENTITY_SCAFFOLD_MODEL_FILE_EXTENSION', '.model');
define('ENTITY_SCAFFOLD_LOG_SUCCESS', 'ok');
define('ENTITY_SCAFFOLD_LOG_ERROR', 'error');

// Always include helper functions file.
require_once dirname(__FILE__) . '/entity_scaffold.helper.inc';
