<?php

/**
 * @file
 * Implementation of Entity Element.
 */

/**
 * Implements hook_entity_info().
 */
function element_entity_info() {
  $return['element'] = array(
    'label' => t('Element'),
    // The entity class and controller class extend the default entity classes.
    'entity class' => 'Element',
    'controller class' => 'ElementController',
    'base table' => 'element',
    'fieldable' => TRUE,
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'element_id',
      'bundle' => 'type',
    ),
    // Bundles are defined by the types below.
    'bundles' => array(),
    'bundle keys' => array('bundle' => 'type'),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'access callback' => 'element_access',
    'module' => 'element',
    // The information below is used by the Controller;
    // which extends the EntityDefaultUIController.
    'admin ui' => array(
      'path' => 'admin/content/element',
      'file' => 'includes/element.admin.inc',
      'controller class' => 'ElementUIController',
      'menu wildcard' => '%element',
    ),
  );
  // The entity that holds information about the entity types.
  $return['element_type'] = array(
    'label' => t('Element Type'),
    'entity class' => 'ElementType',
    'controller class' => 'ElementTypeController',
    'base table' => 'element_type',
    'fieldable' => FALSE,
    'bundle of' => 'element',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'element_type_access',
    'module' => 'element',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/element_types',
      'file' => 'includes/element_type.admin.inc',
      'controller class' => 'ElementTypeUIController',
    ),
  );

  return $return;
}

/**
 * Implements hook_entity_info_alter().
 */
function element_entity_info_alter(&$entity_info) {
  foreach (element_get_types() as $type => $info) {
    $entity_info['element']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/element_types/manage/%element_type',
        'real path' => 'admin/structure/element_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer Element types'),
      ),
    );
  }
}

/**
 * Implements hook_permission().
 */
function element_permission() {
  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity.
  $permissions = array(
    'administer Element types' => array(
      'title' => t('Administer Element types'),
      'description' => t('Create and delete fields for Element types, and set their permissions.'),
    ),
    'administer Element' => array(
      'title' => t('Administer Element'),
      'description' => t('Edit and delete all Element'),
    ),
  );

  // Generate permissions.
  foreach (element_get_types() as $type) {
    $type_name = check_plain($type->type);
    $permissions += array(
      "edit any $type_name Element" => array(
        'title' => t('%type_name: Edit any Element', array('%type_name' => $type->label)),
      ),
      "view any $type_name Element" => array(
        'title' => t('%type_name: View any Element', array('%type_name' => $type->label)),
      ),
    );
  }

  return $permissions;
}

/**
 * Implements hook_theme().
 */
function element_theme() {
  return array(
    'element' => array(
      'render element' => 'elements',
      'template' => 'element',
    ),
  );
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function element_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/structure/element/add'
  // on 'admin/structure/element'.
  if ($root_path == 'admin/content/element') {
    $item = menu_get_item('admin/content/element/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Determines whether the given user has access to a Element.
 *
 * @param string $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 *
 * @param object $entity
 *   Optionally a Element or a Element type to check access for.
 *   If nothing is given, access for all Element is determined.
 *
 * @param object $account
 *   The user to check for. Leave it to NULL to check for the global user.
 *
 * @return bool
 *   Whether access is allowed or not.
 */
function element_access($op, $entity = NULL, $account = NULL) {
  if (user_access('administer Element', $account)) {
    return TRUE;
  }

  if (isset($entity) && $type_name = $entity->type) {
    $op = ($op == 'view') ? 'view' : 'edit';
    if (user_access("$op any $type_name Element", $account)) {
      return TRUE;
    }
  }

  return FALSE;
}

/**
 * Access callback for the entity API.
 */
function element_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer Element types', $account);
}

/**
 * Gets an array of all Element types, keyed by the type name.
 *
 * @param string $type_name
 *   If set, the type with the given name is returned.
 *
 * @return array
 *   Depending whether $type isset, an array of Element types
 *   or a single one.
 */
function element_get_types($type_name = NULL) {
  // entity_load will get the Entity controller for our Element entity
  // and call the load function of that object.
  // We are loading entities by name here.
  $types = entity_load_multiple_by_name('element_type', isset($type_name) ? array($type_name) : FALSE);

  return isset($type_name) ? reset($types) : $types;
}

/**
 * Menu argument loader; Load a Element type by string.
 *
 * @param string $type
 *   The machine-readable name of a Element type to load.
 *
 * @return mixed
 *   A Element type array or FALSE if $type does not exist.
 */
function element_type_load($type) {
  return element_get_types($type);
}

/**
 * Fetch a Element object.
 *
 * @param int $element_id
 *   Integer specifying the element id.
 *
 * @return object
 *   A fully-loaded object or FALSE if it cannot be loaded.
 *
 * @see entity_load_single()
 */
function element_load($element_id) {
  return entity_load_single('element', $element_id);
}

/**
 * Load multiple Element based on certain conditions.
 *
 * @param array $element_ids
 *   An array of Element IDs.
 *
 * @param array $conditions
 *   An array of conditions to match against the element table.
 *
 * @param bool $reset
 *   A boolean indicating that the internal cache should be reset.
 *
 * @return array
 *   An array of objects, indexed by element_id.
 *
 * @see entity_load()
 * @see element_load()
 */
function element_load_multiple($element_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('element', $element_ids, $conditions, $reset);
}

/**
 * Deletes a Element.
 */
function element_delete(Element $element) {
  $element->delete();
}

/**
 * Delete multiple Element.
 *
 * @param array $element_ids
 *   An array of Element IDs.
 */
function element_delete_multiple(array $element_ids) {
  return entity_delete_multiple('element', $element_ids);
}

/**
 * Create a Element object.
 */
function element_create($values = array()) {
  return entity_create('element', $values);
}

/**
 * Saves a Element to the database.
 *
 * @param string $element
 *   The Element object.
 */
function element_save($element) {
  return entity_save('element', $element);
}

/**
 * Saves a Element type to the db.
 */
function element_type_save($type) {
  return entity_save('element_type', $type);
}

/**
 * Deletes a Element type from the db.
 */
function element_type_delete(ElementType $type) {
  $type->delete();
}

/**
 * Menu title callback for showing individual entities.
 */
function element_page_title(Element $element) {
  return $element->label;
}

/**
 * Sets up content to show an individual Element.
 */
function element_page_view($element, $view_mode = 'full') {
  return entity_view('element_type', array($element), $view_mode);
}
